import React from 'react';
import { Text, StyleSheet } from 'react-native';
import { NativeStackScreenProps } from '@react-navigation/native-stack';
import { RootStackParamList } from '../../../app/navigation/types';
import { AppHeader, AppScreen, BrandHeroCard, GradientButton, InfoNotice, SectionCard } from '../../../shared/ui';
import { colors, spacing } from '../../../shared/theme';
type Props = NativeStackScreenProps<RootStackParamList, 'ApplicationIntro'>;
export const ApplicationIntroScreen = ({ navigation }: Props) => <AppScreen><AppHeader title="Nueva solicitud" showBack onBack={() => navigation.goBack()} /><BrandHeroCard title="Comencemos" subtitle="Estás por iniciar una nueva solicitud en CEAMI." centered /><SectionCard><Text style={styles.heading}>Antes de continuar</Text><Text style={styles.body}>Te guiaremos paso a paso para completar tu solicitud. Ten a la mano tu identificación oficial y verifica tu información antes de avanzar.</Text><InfoNotice>Tu proceso será guiado y seguro dentro de la plataforma CEAMI.</InfoNotice></SectionCard><Text style={styles.heading}>Pasos del proceso</Text><SectionCard><Text style={styles.stepTitle}>▣  Validación inicial</Text><Text style={styles.body}>Se revisan los datos básicos del solicitante.</Text><Text style={styles.stepTitle}>▤  Documentación</Text><Text style={styles.body}>Captura tu INE por ambos lados y una selfie.</Text><Text style={styles.stepTitle}>✎  Captura de información</Text><Text style={styles.body}>Completa tus datos generales, familiares y laborales.</Text></SectionCard><GradientButton label="Continuar" onPress={() => navigation.navigate('Documents')} /></AppScreen>;
const styles = StyleSheet.create({ heading: { color: colors.textPrimary, fontSize: 27, fontWeight: '800', marginBottom: spacing.lg }, body: { color: colors.textSecondary, fontSize: 17, lineHeight: 27, marginBottom: spacing.lg }, stepTitle: { color: colors.textPrimary, fontSize: 18, fontWeight: '800', marginTop: spacing.md, marginBottom: spacing.xs } });
