import { ApplicationSubmissionError, assertCanSubmitApplication, canSubmitApplication, documentsProgress, hasCompleteDocuments, hasDuplicateReferencePhones, submissionIssues, wizardProgress } from './application.rules';
import { emptyDocuments, CreditApplication } from './application.types';

const base = (): CreditApplication => ({ id: '1', folio: 'SOL-000001', status: 'draft', createdAt: '', updatedAt: '', documents: emptyDocuments(), signature: { status: 'pending' } });
describe('application rules', () => {
  it('calculates document and wizard progress', () => { const application = base(); application.documents = application.documents.map((item) => ({ ...item, status: 'captured' })); application.generalData = {} as CreditApplication['generalData']; application.familyData = {}; expect(documentsProgress(application)).toBe(3); expect(wizardProgress(application)).toBe(2); expect(hasCompleteDocuments(application)).toBe(true); });
  it('detects duplicated reference phones', () => { const application = base(); application.generalData = { phone: '5512345678' } as CreditApplication['generalData']; application.referencesData = { reference1: { name: 'Ana', address: 'Calle', phone: '5512345678' }, reference2: { name: 'Luis', address: 'Calle', phone: '5587654321' } }; expect(hasDuplicateReferencePhones(application)).toBe(true); });
  it('only allows submission with signature and confirmation', () => { const application = base(); application.documents = application.documents.map((item) => ({ ...item, status: 'captured' })); application.generalData = { date: '2026-07-10', clientName: 'Alejandra Ruiz', curp: 'RUXA900101MDFXXX01', rfc: 'RUXA900101ABC', phoneType: 'mobile', phone: '5512345678', address: 'Calle Uno 10', housingType: 'owned', email: 'alejandra@ceami.mx', maritalStatus: 'single' }; application.familyData = {}; application.workData = { job: 'Comerciante', workAddress: 'Avenida Dos 20', seniority: '3 años', income: 15000, householdExpenses: 5000, otherExpenses: 500, ownsCar: true, bankDebt: 0 }; application.referencesData = { reference1: { name: 'Ana Pérez', address: 'Calle Tres 30', phone: '5587654321' }, reference2: { name: 'Luis Soto', address: 'Calle Cuatro 40', phone: '5567890123' } }; application.signature = { status: 'captured' }; expect(canSubmitApplication(application, false)).toBe(false); expect(canSubmitApplication(application, true)).toBe(true); });
  it('reports a domain reason when a submission is incomplete', () => { const application = base(); expect(submissionIssues(application, false)).toContain('documents_incomplete'); expect(() => assertCanSubmitApplication(application, false)).toThrow(ApplicationSubmissionError); });
});
